export const products = [
  {
    id: 437,
    name: "sdasdasdasdasdas",
    main_image:
      "https://speed4ever.elsaed.aait-d.com/public/storage/images/product/MTrDMtnWyg4DnPFa4V9GOXJJLDGwsBYiGL7wskQ3.jpg",
    rate: 0,
    product_price: 2000,
    user: {
      id: 100,
      username: "speed4ever",
      phone: "966507372797",
      email: "speed4ever@outlook.sa",
      image:
        "https://speed4ever.elsaed.aait-d.com/public/dashboardAssets/images/backgrounds/avatar.jpg",
    },
    category: null,
    qty: 1000,
    is_fav: true,
    is_direct_sale: true,
    is_bid: false,
    auction_id: null,
    bid_value: null,
    end_bid_date: null,
    last_bid_price: null,
    time_remaining: null,
    bidders_count: 0,
    is_auction_finished: false,
  },
  {
    id: 176,
    name: "بنطلون جينز اسود",
    main_image:
      "https://speed4ever.elsaed.aait-d.com/public/storage/images/product/uyFahsGC3RoVo8aTzH2LRAsW3nv2CU3jcCM3xFUR.jpg",
    rate: 0,
    product_price: 500,
    user: {
      id: 98,
      username: "farouk1",
      phone: "96656123456",
      email: "faroukahmed975@gmail.com",
      image:
        "https://speed4ever.elsaed.aait-d.com/public/dashboardAssets/images/backgrounds/avatar.jpg",
    },
    category: null,
    qty: 10,
    is_fav: true,
    is_direct_sale: true,
    is_bid: false,
    auction_id: null,
    bid_value: null,
    end_bid_date: null,
    last_bid_price: null,
    time_remaining: null,
    bidders_count: 0,
    is_auction_finished: false,
  },
  {
    id: 175,
    name: "صالون",
    main_image:
      "https://speed4ever.elsaed.aait-d.com/public/storage/images/product/jSGWMLphNgSKa22WeeGjW6GjOXk8CqrQJ0MpC4to.jpg",
    rate: 0,
    product_price: 2650,
    user: {
      id: 101,
      username: "mohamedgamal12",
      phone: "966509661234",
      email: "mg7383466@gmail.com",
      image:
        "https://speed4ever.elsaed.aait-d.com/public/dashboardAssets/images/backgrounds/avatar.jpg",
    },
    category: {
      id: 10,
      name: "أثاث",
      image:
        "https://speed4ever.elsaed.aait-d.com/public/storage/images/category/sWFUztMnTuYVSr3bKDQX0HxqkYHvuMwY8tMepJ2V.png",
    },
    qty: 5,
    is_fav: true,
    is_direct_sale: true,
    is_bid: false,
    auction_id: null,
    bid_value: null,
    end_bid_date: null,
    last_bid_price: null,
    time_remaining: null,
    bidders_count: 0,
    is_auction_finished: false,
  },
  {
    id: 173,
    name: "انتريه",
    main_image:
      "https://speed4ever.elsaed.aait-d.com/public/storage/images/product/fbSzk6Vyolx7mm4itl58YgCVwc3m8VVqd8qk2O5N.jpg",
    rate: 0,
    product_price: 2150,
    user: {
      id: 101,
      username: "mohamedgamal12",
      phone: "966509661234",
      email: "mg7383466@gmail.com",
      image:
        "https://speed4ever.elsaed.aait-d.com/public/dashboardAssets/images/backgrounds/avatar.jpg",
    },
    category: {
      id: 10,
      name: "أثاث",
      image:
        "https://speed4ever.elsaed.aait-d.com/public/storage/images/category/sWFUztMnTuYVSr3bKDQX0HxqkYHvuMwY8tMepJ2V.png",
    },
    qty: 2,
    is_fav: true,
    is_direct_sale: true,
    is_bid: false,
    auction_id: null,
    bid_value: null,
    end_bid_date: null,
    last_bid_price: null,
    time_remaining: null,
    bidders_count: 0,
    is_auction_finished: false,
  },
  {
    id: 171,
    name: "صالون",
    main_image:
      "https://speed4ever.elsaed.aait-d.com/public/storage/images/product/CYS0pUgwfSD6rBjsUOpEAZKnuJsqck1vQUTWhWjO.jpg",
    rate: 0,
    product_price: 1850,
    user: {
      id: 101,
      username: "mohamedgamal12",
      phone: "966509661234",
      email: "mg7383466@gmail.com",
      image:
        "https://speed4ever.elsaed.aait-d.com/public/dashboardAssets/images/backgrounds/avatar.jpg",
    },
    category: {
      id: 10,
      name: "أثاث",
      image:
        "https://speed4ever.elsaed.aait-d.com/public/storage/images/category/sWFUztMnTuYVSr3bKDQX0HxqkYHvuMwY8tMepJ2V.png",
    },
    qty: 2,
    is_fav: true,
    is_direct_sale: true,
    is_bid: false,
    auction_id: null,
    bid_value: null,
    end_bid_date: null,
    last_bid_price: null,
    time_remaining: null,
    bidders_count: 0,
    is_auction_finished: false,
  },
  {
    id: 168,
    name: "طرابيزة",
    main_image:
      "https://speed4ever.elsaed.aait-d.com/public/storage/images/product/w3D7t3uSLO8naD1Fx7U3z4WL9j4LeNyqEtBW6acv.jpg",
    rate: 0,
    product_price: 650,
    user: {
      id: 101,
      username: "mohamedgamal12",
      phone: "966509661234",
      email: "mg7383466@gmail.com",
      image:
        "https://speed4ever.elsaed.aait-d.com/public/dashboardAssets/images/backgrounds/avatar.jpg",
    },
    category: {
      id: 10,
      name: "أثاث",
      image:
        "https://speed4ever.elsaed.aait-d.com/public/storage/images/category/sWFUztMnTuYVSr3bKDQX0HxqkYHvuMwY8tMepJ2V.png",
    },
    qty: 5,
    is_fav: true,
    is_direct_sale: true,
    is_bid: false,
    auction_id: null,
    bid_value: null,
    end_bid_date: null,
    last_bid_price: null,
    time_remaining: null,
    bidders_count: 0,
    is_auction_finished: false,
  },
  {
    id: 161,
    name: "فلل للبيع في العاصمة الإدارية الجديدة",
    main_image:
      "https://speed4ever.elsaed.aait-d.com/public/storage/images/product/n00DMDTPTqxFwDrMPbZwc8LFYFuJGq7P5SuRgo1M.jpg",
    rate: 0,
    product_price: 500000,
    user: {
      id: 98,
      username: "farouk1",
      phone: "96656123456",
      email: "faroukahmed975@gmail.com",
      image:
        "https://speed4ever.elsaed.aait-d.com/public/dashboardAssets/images/backgrounds/avatar.jpg",
    },
    category: {
      id: 13,
      name: "عقارات",
      image:
        "https://speed4ever.elsaed.aait-d.com/public/storage/images/category/j7Ns76MGUkcEYKrafEzBDcUKHfWcMK0NkMwytaZN.png",
    },
    qty: 3,
    is_fav: true,
    is_direct_sale: true,
    is_bid: false,
    auction_id: null,
    bid_value: null,
    end_bid_date: null,
    last_bid_price: null,
    time_remaining: null,
    bidders_count: 0,
    is_auction_finished: false,
  },
  {
    id: 159,
    name: "iPhone 13 Pro Max",
    main_image:
      "https://speed4ever.elsaed.aait-d.com/public/storage/images/product/CZ0ysXgnjXwpGcu1iFopt2SBOQ1ll2izK4wPh1KM.jpg",
    rate: 0,
    product_price: 18000,
    user: {
      id: 98,
      username: "farouk1",
      phone: "96656123456",
      email: "faroukahmed975@gmail.com",
      image:
        "https://speed4ever.elsaed.aait-d.com/public/dashboardAssets/images/backgrounds/avatar.jpg",
    },
    category: {
      id: 12,
      name: "هواتف",
      image:
        "https://speed4ever.elsaed.aait-d.com/public/storage/images/category/DdXVciD0I35rS4z43jmQX2teZEdXR8ihHuKKuQhx.png",
    },
    qty: 5,
    is_fav: true,
    is_direct_sale: true,
    is_bid: false,
    auction_id: null,
    bid_value: null,
    end_bid_date: null,
    last_bid_price: null,
    time_remaining: null,
    bidders_count: 0,
    is_auction_finished: false,
  },
];